<?php declare(strict_types=1);

namespace Convo\Pckg\Destiny;

use Convo\Core\Factory\AbstractPackageDefinition;

class DestinyPackageDefintion extends AbstractPackageDefinition
{
	const NAMESPACE = 'convo-destiny';

	public function __construct(\Psr\Log\LoggerInterface $logger)
	{
		parent::__construct($logger, self::NAMESPACE, __DIR__);
	}

	public function _initDefintions()
	{
		return parent::_initDefintions(); // TODO: Change the autogenerated stub
	}
}
